"""
Django settings for jobportal project.
 
Generated by 'django-admin startproject' using Django 5.2.
 
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
 
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
 
from pathlib import Path
 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
 
 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
 
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fzjvgpngr%%8@-@^oat@(g(6+4i@jq+u(@2=&j@vyl3!n3wa*5'
 
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
 
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "54.183.89.14"
    ]
 
 
 
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django_extensions',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    # 'jobapp',
    'jobapp.apps.JobappConfig',
    'channels',
]
 
'django_celery_beat',
 
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}
 
 
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   
]

from celery.schedules import crontab
 
CELERY_BEAT_SCHEDULE = {
 
    # ─────────────────────────────
    # WEEKLY EMPLOYER SUMMARY
    # ─────────────────────────────
 
    'weekly-employer-summary': {
 
        'task': (
            'jobapp.tasks.'
            'send_weekly_summary_notifications'
        ),
 
        'schedule': crontab(
            hour=9,
            minute=0,
            day_of_week='monday'
        ),
    },
 
    # ─────────────────────────────
    # AUTO EXPIRE JOBS
    # ─────────────────────────────
 
    'expire-jobs-every-hour': {
 
        'task': (
            'jobapp.tasks.'
            'expire_jobs'
        ),
 
        'schedule': crontab(
            minute=0
        ),
    },
 
    # ─────────────────────────────
    # NOTIFY EXPIRING JOBS
    # ─────────────────────────────
 
    'notify-expiring-jobs': {
 
        'task': (
            'jobapp.tasks.'
            'notify_expiring_jobs'
        ),
 
        'schedule': crontab(
            hour=9,
            minute=0
        ),
    },
}
CELERY_BROKER_URL = 'redis://localhost:6379/0'
 
CELERY_ACCEPT_CONTENT = ['json']
 
CELERY_TASK_SERIALIZER = 'json'
 
CELERY_RESULT_SERIALIZER = 'json'
 
CELERY_TIMEZONE = 'Asia/Kolkata'

# GeoIP DB path (project currently keeps mmdb under jobapp/geoip)
GEOIP_PATH = BASE_DIR / "jobapp" / "geoip"
GEOIP_CITY = "GeoLite2-City.mmdb"
 
CORS_ALLOW_ALL_ORIGINS = False
 
CORS_ALLOW_CREDENTIALS = True
 
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://localhost:5174",
    "https://112m0g3c-5173.inc1.devtunnels.ms",
    "http://54.183.89.14"
   
]
 
 
 
 
ROOT_URLCONF = 'jobportal.urls'
 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
 
ASGI_APPLICATION = 'jobportal.asgi.application'
WSGI_APPLICATION = 'jobportal.wsgi.application'
 
 
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
 
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',  
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'jobportal_dev',
        'USER': 'jobportal_user',
        'PASSWORD': 'Jobportal@01',
        'HOST': '54.183.89.14',
        'PORT': '3306',
        'CONN_MAX_AGE':60,
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}
 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
 
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
 
EMAIL_HOST_USER = 'jobportal709@gmail.com'
EMAIL_HOST_PASSWORD = 'yoka vlvv dnok thor'
 
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
 
 
 
 
 
 
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
 
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 
 
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
 
LANGUAGE_CODE = 'en-us'
 
TIME_ZONE = 'Asia/Kolkata'
 
USE_I18N = True
 
USE_TZ = False
 
 
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
 
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
 
 
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
 
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'jobapp.User'
 
from datetime import timedelta
 
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}
 
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'  
    }
}
 
RAZORPAY_KEY = 'rzp_test_SoLg0asGleZ7ek'
RAZORPAY_SECRET = 'tL6rUUEqZkMjpcK0QKoNiigP'
RAZORPAY_WEBHOOK_SECRET = ''
 
import os
 
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://54.183.89.14")
 
GOOGLE_CLIENT_ID = "105293618059-al95762js6gc2o9umchkb3la0mnirhs1.apps.googleusercontent.com"
#GOOGLE_CLIENT_ID = "146646258104-184rcr7uv1mpttpi8bjf9tjq2r2ijg1i.apps.googleusercontent.com"