import React from "react";
import { Footer } from "../Components-LandingPage/Footer";
import "./JobEmployerHelp.css";
import InvoiceImg from "../assets/Invoicepayment.png";
import { FHeader } from './FHeader';

export const InvoicePaymentHelp = () => {
  const paymentData = {
    title: "How to Manage Invoices & Payments",
    updatedDate: "Updated 27 Feb 2026",
    intro: "Timely and accurate payment processing ensures uninterrupted access to your hiring tools. Use this guide to navigate our billing, reconciliation, and tax documentation process.",

    summary: [
      "<strong>Payment Method:</strong> UPI, Card Payments, Mobile App Store Payments, Electronic Transfers, and Bank Account Linking etc...",
      "<strong>Verify Invoice:</strong> Match with Purchase Orders (PO).",
      "<strong>Validate Tax:</strong> Check PAN and GST details carefully.",
      "<strong>Get Approval:</strong> Route through internal authorization.",
      "<strong>System Record:</strong> Enter data into your ERP or SAP system.",
      "<strong>Schedule Pay:</strong> Set dates based on agreed terms (Net 30).",
      "<strong>Execute Transfer:</strong> Process via ACH or wire transfer.",
      "<strong>Reconcile:</strong> Update records and resolve any disputes."
    ],

    sections: [
      {
        title: "1. Invoice Verification & Data Validation",
        list: [
          "<strong>Receive and Match:</strong> Obtain the invoice via email or portal. Immediately match it against your <strong>Purchase Order (PO)</strong> and goods receipt note to ensure service accuracy.",
          "<strong>Vendor Authentication:</strong> Ensure the vendor profile—including PAN and bank details—is updated. Verify that the invoice numbers and dates match your internal records.",
          "<strong>Tax Compliance:</strong> Check GST details and tax breakdowns. Incorrect tax data can lead to reconciliation issues during audit seasons."
        ]
      },
      {
        title: "2. Authorization & System Entry",
        list: [
          "<strong>Internal Approvals:</strong> Route the validated invoice through your company's necessary internal authorization channels before scheduling payment.",
          "<strong>Accounting Records:</strong> Record the invoice into your Accounting/ERP system (e.g., SAP or Oracle). Accurate data entry here prevents duplicate payments and ensures clear audit trails.",
          "<strong>Scheduling:</strong> Set up the payment date based on your agreed contract terms (e.g., Net 30 or Net 60) to maintain healthy vendor relationships."
        ]
      },
      {
        title: "3. Processing & Reconciliation",
        list: [
          "<strong>Electronic Execution:</strong> Process payments via secure electronic transfers such as <strong>ACH, NEFT, or Wire</strong>. Avoid manual checks where possible to reduce processing time.",
          "<strong>Dispute Resolution:</strong> If discrepancies or duplicate queries arise, pause the payment and contact the billing department immediately for clarification.",
          "<strong>Final Reconciliation:</strong> Perform regular vendor reconciliation to ensure your bank statements perfectly match your internal payment records."
        ]
      },
      {
        title: "💡 Financial Best Practices",
        list: [
          "<strong>Automate Notifications:</strong> Enable billing alerts to receive an automated email as soon as a new invoice is generated by our system.",
          "<strong>Downloadable Receipts:</strong> Always download and save a <strong>PDF copy</strong> of your transaction from the 'Billing' tab for your official tax records.",
          "<strong>Maintain Updated Info:</strong> Ensure your primary credit card or bank link is valid to prevent service interruptions due to failed recurring subscription payments."
        ]
      }
    ]
  };

  return (
    <>
    <FHeader />
      <div className="jobemployerhelp-page">
        <div className="jobemployerhelp-container">
          <h1 className="jobemployerhelp-title">{paymentData.title}</h1>
          <p className="jobemployerhelp-updated">{paymentData.updatedDate}</p>
          <p className="jobemployerhelp-intro">{paymentData.intro}</p>

          <div className="jobemployerhelp-layout" style={{ display: 'flex', gap: '30px', marginBottom: '40px', flexWrap: 'wrap' }}>
            <div className="jobemployerhelp-left" style={{ flex: '1 1 400px' }}>
              <img
                src={InvoiceImg}
                alt="Invoice and Payment Processing Workflow"
                className="jobemployerhelp-hero-img"
                style={{ width: '100%', borderRadius: '12px', boxShadow: '0 4px 10px rgba(0,0,0,0.1)' }}
              />
            </div>

            <div className="jobemployerhelp-right" style={{ flex: '1 1 300px', backgroundColor: '#f4fbf6', padding: '25px', borderRadius: '12px', border: '1px solid #c3e6cb' }}>
              <h2 style={{ marginTop: 0, color: '#155724' }}>Processing Summary</h2>
              <ul className="jobemployerhelp-summary-list" style={{ listStyle: 'none', padding: 0 }}>
                {paymentData.summary.map((item, index) => (
                  <li key={index} style={{ marginBottom: '12px', display: 'flex', alignItems: 'flex-start' }}>
                    <span style={{ color: '#28a745', marginRight: '10px' }}>💰</span>
                    <span dangerouslySetInnerHTML={{ __html: item }} />
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div className="jobemployerhelp-content">
            {paymentData.sections.map((section, index) => (
              <div key={index} className="jobemployerhelp-section" style={{ marginBottom: '40px' }}>
                <h2 style={{ borderBottom: '2px solid #28a745', display: 'inline-block', paddingBottom: '5px', marginBottom: '20px' }}>
                  {section.title}
                </h2>
                {section.list && (
                  <ul className="jobemployerhelp-list" style={{ listStyleType: 'none', paddingLeft: '0' }}>
                    {section.list.map((item, i) => (
                      <li key={i} style={{ marginBottom: '15px', lineHeight: '1.7', color: '#444' }} dangerouslySetInnerHTML={{ __html: item }} />
                    ))}
                  </ul>
                )}
              </div>
            ))}
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
};