# Generated by Django 5.2 on 2026-05-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postajob',
            name='salary',
            field=models.CharField(blank=True, default='Not Disclosed', max_length=100),
        ),
    ]
