# Generated by Django 5.2 on 2026-05-31 04:25

import django.db.models.deletion
import jobapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_alter_postajob_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.BooleanField(default=True)),
                ('email_verification', models.BooleanField(default=True)),
                ('phone_verification', models.BooleanField(default=False)),
                ('domain_restriction', models.BooleanField(default=False)),
                ('allowed_domains', models.JSONField(blank=True, default=jobapp.models.JobseekerPlatformSettings.default_allowed_domains)),
                ('default_role', models.CharField(default='Job Seeker', max_length=100)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='Active', max_length=50)),
                ('profile_visibility', models.CharField(choices=[('Public', 'Public'), ('Employers Only', 'Employers Only'), ('Private', 'Private')], default='Employers Only', max_length=50)),
                ('resume_visibility', models.CharField(choices=[('Public', 'Public'), ('Employers Only', 'Employers Only'), ('Private', 'Private')], default='Employers Only', max_length=50)),
                ('anonymous_profile', models.BooleanField(default=False)),
                ('profile_completion_required', models.CharField(default='0 %', max_length=20)),
                ('salary_visibility', models.BooleanField(default=True)),
                ('company_reviews', models.BooleanField(default=True)),
                ('application_status_tracking', models.BooleanField(default=True)),
                ('similar_jobs', models.BooleanField(default=True)),
                ('career_advice', models.BooleanField(default=True)),
                ('easy_apply', models.BooleanField(default=True)),
                ('save_jobs', models.BooleanField(default=True)),
                ('max_applications', models.PositiveIntegerField(default=30)),
                ('application_expiry_days', models.PositiveIntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationChannelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notif', models.BooleanField(default=True)),
                ('inapp_notif', models.BooleanField(default=True)),
                ('sms_notif', models.BooleanField(default=False)),
                ('push_notif', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('user_mgmt', 'User Management'), ('job_mgmt', 'Job Management'), ('apps', 'Applications'), ('companies', 'Companies'), ('reports', 'Reports'), ('general', 'General')], max_length=30, unique=True)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=True)),
                ('sms', models.BooleanField(default=False)),
                ('push', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('admin_2fa', 'Admin 2FA'), ('login', 'Login')], max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/banner/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='brand_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyverification',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company/gst/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('user_mgmt', 'User Management'), ('job_mgmt', 'Job Management'), ('apps', 'Applications'), ('companies', 'Companies'), ('reports', 'Reports'), ('general', 'General'), ('new_signup', 'New Signup'), ('alert', 'Alert'), ('announcement', 'Announcement'), ('weekly_summary', 'Weekly Summary')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postajob',
            name='expiry_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='postajob',
            name='expiry_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='postajob',
            name='expiry_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postajob',
            name='is_expired',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='postajob',
            name='last_date_to_apply',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_expiry_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('job_alert', 'Job Alert'), ('application', 'Application Update'), ('system', 'System Notification'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected'), ('complaint', 'Complaint'), ('announcement', 'Announcement')], default='system', max_length=50),
        ),
        migrations.CreateModel(
            name='AdminAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('2FA_ENABLED', '2FA Enabled'), ('2FA_DISABLED', '2FA Disabled'), ('OTP_FAILED', 'OTP Failed'), ('DEVICE_REVOKED', 'Device Revoked'), ('DEVICE_ADDED', 'Device Added')], max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdminQuietHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('start_time', models.TimeField(default='22:00')),
                ('end_time', models.TimeField(default='07:00')),
                ('timezone', models.CharField(choices=[('Asia/Kolkata', '(UTC +05:30) Asia/Kolkata'), ('America/Los_Angeles', '(UTC -08:00) America/Los_Angeles'), ('UTC', '(UTC +00:00) UTC'), ('Europe/London', '(UTC +01:00) Europe/London'), ('Europe/Berlin', '(UTC +02:00) Europe/Berlin')], default='Asia/Kolkata', max_length=100)),
                ('active_days', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminTrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=20)),
                ('refresh_token_jti', models.CharField(blank=True, max_length=255)),
                ('is_trusted', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_reason', models.CharField(choices=[('IP_CONFLICT', 'IP Conflict'), ('RESUME_BOT', 'Resume Bot'), ('FRAUDULENT_CREDS', 'Fraudulent Credentials')], max_length=50)),
                ('detected_method', models.TextField()),
                ('risk_level', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MODERATE', 'Moderate')], max_length=20)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='jobapp.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('inapp', 'In App'), ('push', 'Push'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('provider_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='jobapp.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_delivery_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(unique=True)),
                ('platform', models.CharField(choices=[('web', 'Web Browser'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('review', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobapp.companyprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='EmployerPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Hold', 'Hold'), ('Deactivated', 'Deactivated')], default='Hold', max_length=15)),
                ('employer_registration', models.BooleanField(default=True)),
                ('email_verification', models.BooleanField(default=True)),
                ('mobile_verification', models.BooleanField(default=False)),
                ('approval_type', models.CharField(choices=[('Manual Type', 'Manual Type'), ('Automatic', 'Automatic')], default='Manual Type', max_length=20)),
                ('req_company_cert', models.BooleanField(default=False)),
                ('req_gst_cert', models.BooleanField(default=False)),
                ('req_business_email', models.BooleanField(default=False)),
                ('req_company_website', models.BooleanField(default=False)),
                ('allow_multiple_company', models.BooleanField(default=False)),
                ('allow_multiple_users', models.BooleanField(default=False)),
                ('show_company_reviews', models.BooleanField(default=False)),
                ('enable_company_branding', models.BooleanField(default=False)),
                ('featured_employer_option', models.BooleanField(default=False)),
                ('notif_email', models.BooleanField(default=False)),
                ('notif_new_signups', models.BooleanField(default=False)),
                ('notif_alerts', models.BooleanField(default=False)),
                ('notif_announcements', models.BooleanField(default=False)),
                ('notif_weekly_summary', models.BooleanField(default=False)),
                ('job_expire_days', models.PositiveIntegerField(default=30)),
                ('max_job_posts', models.PositiveIntegerField(default=10)),
                ('featured_job_limit', models.PositiveIntegerField(default=3)),
                ('allow_edit_after_approval', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_settings', to='jobapp.plan')),
            ],
            options={
                'ordering': ['plan'],
                'unique_together': {('plan', 'account_status')},
            },
        ),
    ]
