# Generated by Django 5.2 on 2026-06-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_jobseekerplatformsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profile_photos/'),
        ),
    ]
